name: Well done message

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Create comments on PR
        run: |
          cat << EOF > comments
          @${{ github.event.pull_request.user.login }}
          以上でこの課題は終了です．お疲れ様でした！
          EOF
      - name: Post comments on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run:
          gh pr comment -F ./comments "${URL}"
